# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\pyproj\archer_ballistics_constructor\ui_templates\footer.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
import qtawesome as qta


class Ui_FooterWidget(object):
    def setup_ui(self, FooterWidget):
        FooterWidget.setObjectName("FooterWidget")
        FooterWidget.resize(675, 42)
        FooterWidget.setMaximumSize(QtCore.QSize(16777215, 42))
        FooterWidget.setStyleSheet("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(FooterWidget)
        self.horizontalLayout.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout.setObjectName("horizontalLayout")
        # self.Preferences = QtWidgets.QToolButton(FooterWidget)
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.Preferences.sizePolicy().hasHeightForWidth())
        # self.Preferences.setSizePolicy(sizePolicy)
        # icon = QtGui.QIcon()
        # icon.addPixmap(QtGui.QPixmap(":/custom/res/custom/tools.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.Preferences.setIcon(qta.icon('mdi6.cog', color='white'))
        # self.Preferences.setObjectName("Preferences")
        # self.horizontalLayout.addWidget(self.Preferences)

        self.retranslate_ui(FooterWidget)
        QtCore.QMetaObject.connectSlotsByName(FooterWidget)

    def retranslate_ui(self, FooterWidget):
        _translate = QtCore.QCoreApplication.translate
        FooterWidget.setWindowTitle(_translate("FooterWidget", "Form"))
        # self.Preferences.setToolTip(_translate("FooterWidget", "Preferences"))
        # self.Preferences.setText(_translate("FooterWidget", "Settings"))
