# -*- coding: utf-8 -*-
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtWidgets
from py_ballisticcalc import Unit

from py_balcalc.ui.custom_widgets.unit_sb import UnitSpinBox


class Ui_weapon(object):
    def setupUi(self, weapon):
        weapon.setObjectName("weapon")
        weapon.resize(500, 130)
        self.gridLayout = QtWidgets.QGridLayout(weapon)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.rifleGroupBox = QtWidgets.QGroupBox(weapon)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rifleGroupBox.sizePolicy().hasHeightForWidth())
        self.rifleGroupBox.setSizePolicy(sizePolicy)
        self.rifleGroupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.rifleGroupBox.setCheckable(True)
        self.rifleGroupBox.setObjectName("rifleGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.rifleGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_67 = QtWidgets.QLabel(self.rifleGroupBox)
        self.label_67.setObjectName("label_67")
        self.gridLayout_2.addWidget(self.label_67, 2, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.rifleGroupBox)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 0, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.rifleGroupBox)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 1, 0, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.rifleGroupBox)
        self.label_68.setObjectName("label_68")
        self.gridLayout_2.addWidget(self.label_68, 3, 0, 1, 1)
        self.rightTwist = QtWidgets.QRadioButton(self.rifleGroupBox)
        self.rightTwist.setEnabled(True)
        self.rightTwist.setChecked(True)
        self.rightTwist.setObjectName("rightTwist")
        self.gridLayout_2.addWidget(self.rightTwist, 3, 2, 1, 1)
        self.leftTwist = QtWidgets.QRadioButton(self.rifleGroupBox)
        self.leftTwist.setObjectName("leftTwist")
        self.gridLayout_2.addWidget(self.leftTwist, 3, 3, 1, 1)
        self.caliberName = QtWidgets.QLineEdit(self.rifleGroupBox)
        self.caliberName.setMaxLength(20)
        self.caliberName.setObjectName("caliberName")
        self.gridLayout_2.addWidget(self.caliberName, 1, 1, 1, 2)
        self.caliberShort = QtWidgets.QLineEdit(self.rifleGroupBox)
        self.caliberShort.setMinimumSize(QtCore.QSize(0, 0))
        self.caliberShort.setMaxLength(8)
        self.caliberShort.setObjectName("caliberShort")
        self.gridLayout_2.addWidget(self.caliberShort, 1, 3, 1, 1)
        self.rifleName = QtWidgets.QLineEdit(self.rifleGroupBox)
        self.rifleName.setMaxLength(20)
        self.rifleName.setFrame(True)
        self.rifleName.setObjectName("rifleName")
        self.gridLayout_2.addWidget(self.rifleName, 0, 1, 1, 3)
        self.twist = UnitSpinBox(self.rifleGroupBox, Unit.INCH(10), 'unit/twist')
        self.twist.setObjectName("twistUnits")
        self.gridLayout_2.addWidget(self.twist, 3, 1, 1, 1)
        self.sh = UnitSpinBox(self.rifleGroupBox, Unit.CENTIMETER(9), 'unit/sight_height')
        self.sh.setObjectName("sh")
        self.gridLayout_2.addWidget(self.sh, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.rifleGroupBox, 0, 0, 1, 1)

        self.retranslateUi(weapon)
        QtCore.QMetaObject.connectSlotsByName(weapon)

    def retranslateUi(self, weapon):
        _translate = QtCore.QCoreApplication.translate
        weapon.setWindowTitle(_translate("weapon", "Form"))
        self.rifleGroupBox.setTitle(_translate("weapon", "Rifle"))
        self.label_67.setText(_translate("weapon", "Sight height:"))
        self.label_22.setText(_translate("weapon", "Name:"))
        self.label_23.setText(_translate("weapon", "Caliber:"))
        self.label_68.setText(_translate("weapon", "Twist:"))
        self.rightTwist.setText(_translate("weapon", "Right"))
        self.leftTwist.setText(_translate("weapon", "Left"))
