# -*- coding: utf-8 -*-
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtWidgets
import qtawesome as qta


class Ui_addButton(object):
    def setupUi(self, Ui_addButton):
        Ui_addButton.setObjectName("Ui_addButton")
        # Ui_addButton.resize(380, 28)
        # Ui_addButton.setMaximumSize(QtCore.QSize(386, 16777215))
        Ui_addButton.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(Ui_addButton)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.add = QtWidgets.QPushButton(Ui_addButton)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add.sizePolicy().hasHeightForWidth())
        self.add.setSizePolicy(sizePolicy)
        # self.add.setMinimumSize(QtCore.QSize(0, 0))
        # self.add.setMaximumSize(QtCore.QSize(16777215, 16777215))
        # icon = QtGui.QIcon()
        # icon.addPixmap(QtGui.QPixmap(":/icons/res/drawable-hdpi-v4/addbtn_menu21b.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add.setIcon(qta.icon('mdi6.file-outline', color='grey'))
        self.add.setIconSize(QtCore.QSize(20, 20))
        self.add.setObjectName("add")
        self.gridLayout.addWidget(self.add, 0, 0, 1, 1)

        self.retranslateUi(Ui_addButton)
        QtCore.QMetaObject.connectSlotsByName(Ui_addButton)

    def retranslateUi(self, Ui_addButton):
        _translate = QtCore.QCoreApplication.translate
        Ui_addButton.setWindowTitle(_translate("Ui_addButton", "Form"))
        self.add.setText(_translate("Ui_addButton", "Open file"))
