# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_templates\profile_current.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtWidgets


class Ui_profileCurrent(object):
    def setupUi(self, profileCurrent):
        profileCurrent.setObjectName("profileCurrent")
        profileCurrent.resize(474, 451)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(profileCurrent.sizePolicy().hasHeightForWidth())
        profileCurrent.setSizePolicy(sizePolicy)
        profileCurrent.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(profileCurrent)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget_2 = QtWidgets.QTabWidget(profileCurrent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setStyleSheet("")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.munition_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.munition_tab.sizePolicy().hasHeightForWidth())
        self.munition_tab.setSizePolicy(sizePolicy)
        self.munition_tab.setStyleSheet("")
        self.munition_tab.setObjectName("munition_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.munition_tab)
        self.gridLayout_5.setContentsMargins(6, 6, 6, 3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tabWidget_2.addTab(self.munition_tab, "")
        self.conditions_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.conditions_tab.sizePolicy().hasHeightForWidth())
        self.conditions_tab.setSizePolicy(sizePolicy)
        self.conditions_tab.setObjectName("conditions_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.conditions_tab)
        self.gridLayout_2.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget_2.addTab(self.conditions_tab, "")
        self.gridLayout.addWidget(self.tabWidget_2, 0, 0, 1, 1)

        self.retranslateUi(profileCurrent)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(profileCurrent)

    def retranslateUi(self, profileCurrent):
        _translate = QtCore.QCoreApplication.translate
        profileCurrent.setWindowTitle(_translate("profileCurrent", "Form"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.munition_tab), _translate("profileCurrent", "Current profile"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.conditions_tab), _translate("profileCurrent", "Zeroing conditions"))
