# -*- coding: utf-8 -*-
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtWidgets


class Ui_profilesTab(object):
    def setupUi(self, profiles_tab):
        profiles_tab.setObjectName("profiles_tab")
        profiles_tab.resize(463, 365)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(profiles_tab.sizePolicy().hasHeightForWidth())
        profiles_tab.setSizePolicy(sizePolicy)
        profiles_tab.setMinimumSize(QtCore.QSize(0, 0))
        profiles_tab.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(profiles_tab)
        self.gridLayout.setContentsMargins(6, 6, 6, 6)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")

        self.retranslateUi(profiles_tab)
        QtCore.QMetaObject.connectSlotsByName(profiles_tab)

    def retranslateUi(self, profilesTab):
        _translate = QtCore.QCoreApplication.translate
        profilesTab.setWindowTitle(_translate("profiles_tab", "Form"))
